# Generated by Django 4.2.7 on 2023-12-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_education_gpa_obtained_education_gpa_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
